on:
  pull_request:
    types: [opened, synchronize]

jobs:
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: EsLint
        uses: betrybe/eslint-linter-action@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  stylelint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: Stylelint
        uses: betrybe/stylelint-linter-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  evaluator_job:
    name: Evaluator job
    runs-on: ubuntu-18.04
    needs: [eslint, stylelint]
    steps:
      - uses: actions/checkout@v2  
      - name: Evaluator step
        id: evaluator
        uses: betrybe/react-scripts-evaluator-action@v6
        with:
          repository-test-name: 'betrybe/sd-0x-project-frontend-online-store-tests'
          repository-test-branch: 'master'
        env:
          GITHUB_USER_TEST: ${{ github.actor }} 
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: staging
          pr-number: ${{ github.event.number }}
